<?xml version="1.0" encoding="utf-8"?><Database Name="Test" Class="TestContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=QJ08039878;Initial Catalog=Test;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="paterno" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="materno" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ingreso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="genero" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>